### ISSUE TITLE
Sort box doesn't have background color set

### ISSUE THREAD

**Issue by Blaksey** [RaitaroH/MyAnimeList-DeepDark#1]
![image](https://user-images.githubusercontent.com/2694815/48011681-4f2d3080-e0ee-11e8-8ccf-5db195d32cf7.png)

This can easily be fixed by just adding, I would have just submitted a PR but not sure where you want it organized into your CSS file. 

```
.seasonal-sort-order-block 
{
        background-color: var(--second-background) !important;
}
```

**Comment by RaitaroH** [comment]
Fixed in 2d8c31a
