### ISSUE TITLE
Some issues with the ranking section

### ISSUE THREAD

**Issue by sprite-1** [RaitaroH/MyAnimeList-DeepDark#12]
![image](https://user-images.githubusercontent.com/33685433/66939125-0ce9ce80-f075-11e9-87c2-cac53a30674a.png)

**Comment by RaitaroH** [comment]
Even after login and adding this to reading like above I can't reproduce. Make sure you are up-to-date from the github source.
![image](https://user-images.githubusercontent.com/19552720/67090445-c9957a00-f1b2-11e9-8ff5-114bbd54f4df.png)

**Comment by sprite-1** [comment]
Okay that is weird, the issue seems to have fixed itself. I guess it was a temporary issue on MAL's side 🤔Sorry for the trouble!
