### ISSUE TITLE
Option to exclude anime and manga lists from the theme

### ISSUE THREAD

**Issue by mechagomizilla** [RaitaroH/MyAnimeList-DeepDark#2]
It's not the case of my own list, but a lot of people have the default theme enabled or might have other themes that do not look great with your theme. I am currently using BreezeDark and it's great, but I used the following formula in the declaration to exclude any lists from the theme:
@-moz-document regexp("https://myanimelist.net/(?!(animelist|mangalist|ownlist/style/theme)).*")
You might want to consider making it the default option or inserting a variable so that it can be disabled if the user wants it.

**Comment by mechagomizilla** [comment]
Fixed on pull request #5

**Comment by reitenth** [comment]
im not seeing a setting to include these pages? thanks
