### ISSUE TITLE
MAL DeepDark - Underline BBcode not working

### ISSUE THREAD

**Issue by icarusivys** [RaitaroH/MyAnimeList-DeepDark#21]
Hey, firstly I love your dark mode for the site and all the customizations that go with it. I just have one tiny bit of a problem bothering me and that is, the underline bbcode not appearing when the theme is applied. `underline bbcode = [u][/u]`

![Screenshot 2021-02-20 040451](https://user-images.githubusercontent.com/79343240/108577198-3a155380-7331-11eb-83e4-3135abb06a55.jpg)
**This is without the theme.**

![Screenshot 2021-02-20 040510](https://user-images.githubusercontent.com/79343240/108577211-46011580-7331-11eb-8883-dae7a031ddd2.jpg)
**This is with the theme.**

I was hoping this could get fixed by any chance? **Keep up the good work, I appreciate it a lot. Thank you.**

**Comment by ShadyDeth** [comment]
Added underline support. Will add strike-through at a later time with some more code rework.
