### ISSUE TITLE
Search button not the same size as the search bar

### ISSUE THREAD

**Issue by mechagomizilla** [RaitaroH/MyAnimeList-DeepDark#3]
The search button's height is the default 20px rather than the 22px set for the rest of the search bar.
It can be fixed by adding ".page-common #searchBar.searchBar #topSearchButon" to line 518 like this:

Lines 518 to 521:

    .page-common #searchBar.searchBar #topSearchValue, .page-common #searchBar.searchBar .form-select-outer, .page-common #searchBar.searchBar #topSearchButon
    {
        height: 22px !important;
    }

**Comment by RaitaroH** [comment]
Why not just make a pull request?

**Comment by mechagomizilla** [comment]
I'm submitting a pull request for issues #2 and #3 in a few minutes.

**Comment by mechagomizilla** [comment]
Fixed on pull request #5
