### ISSUE TITLE
New update on review system disabled review's dark backgrounds while using the script

### ISSUE THREAD

**Issue by Yakarup** [RaitaroH/MyAnimeList-DeepDark#30]
The new update on the review system broke a part of the CSS script for the review section. Now the reviews' backgrounds are white instead of black.
![Capture](https://user-images.githubusercontent.com/67720001/182458671-f04f8dad-ac93-4852-b720-9a209b0dc7a5.PNG)

**Comment by ShadyDeth** [comment]
Thanks for the info. Will get it fixed soon.

**Comment by ShadyDeth** [comment]
Review page fixed with #31
