### ISSUE TITLE
Border styling incomplete in the top airing and upcoming anime on the panel page if placed left

### ISSUE THREAD

**Issue by mechagomizilla** [RaitaroH/MyAnimeList-DeepDark#4]
Sorry, I'm doing this because your theme is great. I'm only starting to get into the styling community and I've seen you around a lot. Thank you for the time you put into you themes.
As for this issue, I'm fixing it for myself whenever I get the time, but I haven't done it yet, so here's a screenshot: 

![screenshot](https://i.imgur.com/Qlgqp9G.png)

**Comment by mechagomizilla** [comment]
I could work on this myself if I have the free time. Otherwise, the solution is to always have the rosters on the right.

**Comment by RaitaroH** [comment]
So you say "Top airing" right? 
https://myanimelist.net/topanime.php?type=airing
This that is?
For me the page looks way different. Ah well... look at the date XD
I will close this but if you have some other page instead of the one I mentioned then reopen.
