### ISSUE TITLE
New MAL forums are white and unreadable

### ISSUE THREAD

**Issue by kingomri1234** [RaitaroH/MyAnimeList-DeepDark#56]
Because MAL changed how forums work, all the text is white with a white background.

**Comment by ShadyDeth** [comment]
Not home right now so I can't check, but are you running the most updated version of theme? A few weeks ago the updateurl was changed so anything older than that doesn't have the latest fixes.

**Comment by kingomri1234** [comment]
My bad, I tried to reinstall/update it from the button and not the code itself. Thanks for your help...
