### ISSUE TITLE
Gitlab sync

### ISSUE THREAD

**Issue by ShadyDeth** [RaitaroH/MyAnimeList-DeepDark#67]
Hey @RaitaroH, could you fix the sync for this repo on GitLab.

Updates stopped getting pushed to GitLab so I changed the updateurl to GitHub to still push updates, but a lot of people are still on the old url and not getting updates.

**Comment by RaitaroH** [comment]
Hey @ShadyDeth, thank you for the info.
It would seem that pull and bidirectional mirroring have become premium tier only. See https://docs.gitlab.com/ee/user/project/repository/mirror/pull.html

I have doubled checked in my interface, and I cannot change to pull.
![image](https://user-images.githubusercontent.com/19552720/208070707-d1c3273b-bf14-43aa-82f2-a7c13ec6a9bf.png)

I have checked in other repos, and the mirror is gone, though for DuckDuckGo for example I still see a commit from a week ago, which is interesting. YouTube for example is behind 4 months, as is MAL.

For me, gitlab was for mirroring purposes. Under the new terms I will either:
1. add an update to all my repositories on gitlab to inform people to go to github and likely archive everything (if not there already, change the update link to github)
3. delete my account entirely, which might be easier

**Comment by RaitaroH** [comment]
I suppose 2 workarounds are possible:
1. github actions
2. a custom script on my end

@ShadyDeth what do you think? Personally I would rather just close my gitlab account to avoid any headaches.

**Comment by ShadyDeth** [comment]
I personally would update GitHub and GitLab repos to point to GitHub for the updateurl so users can get on the correct updated versions.

And if you still want to get rid of GitLab, maybe give them a few weeks/months to do so and then delete it.

**Comment by RaitaroH** [comment]
I think for the most part, my themes should point to github.
I will fix anything that doesn't and likely axe gitlab.

**Comment by RaitaroH** [comment]
I have manually, and forcefully, updated gitlab mal for now.
I will add some info to the readme of my repos to point to github and likely archive them.
